name: main

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - run: sbt test
    - uses: actions/setup-node@v2.1.5
    - run: |
        cd test
        npm i
        bin/tes
